[build]
target = "./index.html"
sass-flags = ["--style", "compressed"]

[watch]
ignore = ["./src-tauri"]

[serve]
address = "127.0.0.1"
port = 1420
open = false
sass-flags = ["--style", "compressed"]
